; ============================================================
; Atari 2600 Music Data
; Song: Into the Light — Forest of Mysteries OST
; Generated by Atari Sound Editor
; ============================================================

; NOTE CODE FORMAT: [driverCode(3 bits)][frequency(5 bits)]
; Driver codes:
;   000 = Square  (AUDC=4)    001 = Bass    (AUDC=6)
;   010 = Pitfall (AUDC=7)    011 = Noise   (AUDC=8)
;   100 = Buzz    (AUDC=15)   101 = Lead    (AUDC=12)
;   110 = Saw     (AUDC=1)    111 = Engine  (AUDC=3)
;   $00 = Rest (silence)

Into_the_Light_TEMPO    = 7   ; frames per step (NTSC 60fps)
Into_the_Light_NUM_PATS = 9

; ============================================================
; PATTERN DATA
; ============================================================

; Pattern: You Made It (16 steps)
Into_the_Light_You_Made_It_len = 16

Into_the_Light_You_Made_It_v0_notes:
    .byte $9E, $00, $3A, $00, $9E, $00, $28, $86, $9E, $00, $29, $00, $9E, $00, $28, $86  ; voice 0 note codes

Into_the_Light_You_Made_It_v0_vols:
    .byte $0C, $00, $0A, $00, $0C, $00, $0A, $0A, $0C, $00, $0A, $00, $0C, $00, $0A, $0A  ; voice 0 volumes

Into_the_Light_You_Made_It_v1_notes:
    .byte $1E, $19, $16, $19, $1E, $00, $AC, $00, $B6, $1E, $00, $19, $16, $00, $19, $00  ; voice 1 note codes

Into_the_Light_You_Made_It_v1_vols:
    .byte $0C, $0C, $0C, $0B, $0B, $00, $0B, $00, $0B, $0C, $00, $0C, $0C, $00, $0B, $00  ; voice 1 volumes

; Pattern: Celebration (16 steps)
Into_the_Light_Celebration_len = 16

Into_the_Light_Celebration_v0_notes:
    .byte $9E, $60, $2B, $60, $9E, $00, $28, $86, $9E, $60, $29, $60, $9E, $00, $28, $86  ; voice 0 note codes

Into_the_Light_Celebration_v0_vols:
    .byte $0C, $08, $0A, $08, $0C, $00, $0A, $0A, $0C, $08, $0A, $08, $0C, $00, $0A, $0A  ; voice 0 volumes

Into_the_Light_Celebration_v1_notes:
    .byte $16, $00, $19, $00, $1E, $00, $AC, $B6, $1E, $19, $00, $16, $00, $19, $1E, $00  ; voice 1 note codes

Into_the_Light_Celebration_v1_vols:
    .byte $0C, $00, $0B, $00, $0B, $00, $0B, $0B, $0C, $0C, $00, $0C, $00, $0B, $0B, $00  ; voice 1 volumes

; Pattern: Triumphant Flourish (16 steps)
Into_the_Light_Triumphant_Flourish_len = 16

Into_the_Light_Triumphant_Flourish_v0_notes:
    .byte $9E, $00, $2B, $00, $9E, $60, $27, $00, $9E, $00, $28, $60, $9E, $00, $3A, $86  ; voice 0 note codes

Into_the_Light_Triumphant_Flourish_v0_vols:
    .byte $0C, $00, $0A, $00, $0C, $08, $0A, $00, $0C, $00, $0A, $08, $0C, $00, $0A, $0B  ; voice 0 volumes

Into_the_Light_Triumphant_Flourish_v1_notes:
    .byte $B6, $1E, $19, $16, $15, $16, $00, $19, $1E, $19, $16, $00, $19, $16, $19, $1E  ; voice 1 note codes

Into_the_Light_Triumphant_Flourish_v1_vols:
    .byte $0B, $0B, $0C, $0C, $0C, $0C, $00, $0C, $0C, $0B, $0B, $00, $0C, $0C, $0C, $0C  ; voice 1 volumes

; ============================================================
; ARRANGEMENT TABLE
; Each entry = 9 bytes: v0_notes, v0_vols, v1_notes, v1_vols (words) + length (byte)
; ============================================================

Into_the_Light_arrangement:
    ; arrangement[0] = You Made It
    .word Into_the_Light_You_Made_It_v0_notes
    .word Into_the_Light_You_Made_It_v0_vols
    .word Into_the_Light_You_Made_It_v1_notes
    .word Into_the_Light_You_Made_It_v1_vols
    .byte Into_the_Light_You_Made_It_len
    ; arrangement[1] = You Made It
    .word Into_the_Light_You_Made_It_v0_notes
    .word Into_the_Light_You_Made_It_v0_vols
    .word Into_the_Light_You_Made_It_v1_notes
    .word Into_the_Light_You_Made_It_v1_vols
    .byte Into_the_Light_You_Made_It_len
    ; arrangement[2] = Celebration
    .word Into_the_Light_Celebration_v0_notes
    .word Into_the_Light_Celebration_v0_vols
    .word Into_the_Light_Celebration_v1_notes
    .word Into_the_Light_Celebration_v1_vols
    .byte Into_the_Light_Celebration_len
    ; arrangement[3] = You Made It
    .word Into_the_Light_You_Made_It_v0_notes
    .word Into_the_Light_You_Made_It_v0_vols
    .word Into_the_Light_You_Made_It_v1_notes
    .word Into_the_Light_You_Made_It_v1_vols
    .byte Into_the_Light_You_Made_It_len
    ; arrangement[4] = Celebration
    .word Into_the_Light_Celebration_v0_notes
    .word Into_the_Light_Celebration_v0_vols
    .word Into_the_Light_Celebration_v1_notes
    .word Into_the_Light_Celebration_v1_vols
    .byte Into_the_Light_Celebration_len
    ; arrangement[5] = Triumphant Flourish
    .word Into_the_Light_Triumphant_Flourish_v0_notes
    .word Into_the_Light_Triumphant_Flourish_v0_vols
    .word Into_the_Light_Triumphant_Flourish_v1_notes
    .word Into_the_Light_Triumphant_Flourish_v1_vols
    .byte Into_the_Light_Triumphant_Flourish_len
    ; arrangement[6] = Celebration
    .word Into_the_Light_Celebration_v0_notes
    .word Into_the_Light_Celebration_v0_vols
    .word Into_the_Light_Celebration_v1_notes
    .word Into_the_Light_Celebration_v1_vols
    .byte Into_the_Light_Celebration_len
    ; arrangement[7] = Triumphant Flourish
    .word Into_the_Light_Triumphant_Flourish_v0_notes
    .word Into_the_Light_Triumphant_Flourish_v0_vols
    .word Into_the_Light_Triumphant_Flourish_v1_notes
    .word Into_the_Light_Triumphant_Flourish_v1_vols
    .byte Into_the_Light_Triumphant_Flourish_len
    ; arrangement[8] = You Made It
    .word Into_the_Light_You_Made_It_v0_notes
    .word Into_the_Light_You_Made_It_v0_vols
    .word Into_the_Light_You_Made_It_v1_notes
    .word Into_the_Light_You_Made_It_v1_vols
    .byte Into_the_Light_You_Made_It_len

; ── MUSIC_INIT_INTO_THE_LIGHT ────────────────────────────────────
; Set song parameters and reset playback to the beginning.
; Clobbers: A
MUSIC_INIT_INTO_THE_LIGHT:
    lda #<Into_the_Light_arrangement
    sta MUS_ARR_PTR
    lda #>Into_the_Light_arrangement
    sta MUS_ARR_PTR+1
    lda #Into_the_Light_TEMPO
    sta MUS_TEMPO
    lda #Into_the_Light_NUM_PATS
    sta MUS_NUM_PATS
    jsr MUSIC_INIT
    rts