; ============================================================
; Atari 2600 Music Data
; Song: Whispering Trees — Forest of Mysteries OST
; Generated by Atari Sound Editor
; ============================================================

; NOTE CODE FORMAT: [driverCode(3 bits)][frequency(5 bits)]
; Driver codes:
;   000 = Square  (AUDC=4)    001 = Bass    (AUDC=6)
;   010 = Pitfall (AUDC=7)    011 = Noise   (AUDC=8)
;   100 = Buzz    (AUDC=15)   101 = Lead    (AUDC=12)
;   110 = Saw     (AUDC=1)    111 = Engine  (AUDC=3)
;   $00 = Rest (silence)

Whispering_Trees_TEMPO    = 9   ; frames per step (NTSC 60fps)
Whispering_Trees_NUM_PATS = 10

; ============================================================
; PATTERN DATA
; ============================================================

; Pattern: Night Air (16 steps)
Whispering_Trees_Night_Air_len = 16

Whispering_Trees_Night_Air_v0_notes:
    .byte $00, $00, $CA, $00, $00, $00, $00, $00, $00, $00, $00, $00, $CC, $00, $00, $00  ; voice 0 note codes

Whispering_Trees_Night_Air_v0_vols:
    .byte $00, $00, $05, $00, $00, $00, $00, $00, $00, $00, $00, $00, $05, $00, $00, $00  ; voice 0 volumes

Whispering_Trees_Night_Air_v1_notes:
    .byte $BE, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $B9, $00, $00, $00, $00  ; voice 1 note codes

Whispering_Trees_Night_Air_v1_vols:
    .byte $07, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $07, $00, $00, $00, $00  ; voice 1 volumes

; Pattern: Rustling (16 steps)
Whispering_Trees_Rustling_len = 16

Whispering_Trees_Rustling_v0_notes:
    .byte $DE, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $CA  ; voice 0 note codes

Whispering_Trees_Rustling_v0_vols:
    .byte $05, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $05  ; voice 0 volumes

Whispering_Trees_Rustling_v1_notes:
    .byte $00, $00, $00, $00, $B5, $00, $00, $00, $00, $00, $00, $00, $00, $00, $BC, $00  ; voice 1 note codes

Whispering_Trees_Rustling_v1_vols:
    .byte $00, $00, $00, $00, $07, $00, $00, $00, $00, $00, $00, $00, $00, $00, $06, $00  ; voice 1 volumes

; Pattern: Something Moves (16 steps)
Whispering_Trees_Something_Moves_len = 16

Whispering_Trees_Something_Moves_v0_notes:
    .byte $00, $00, $00, $CC, $00, $00, $00, $00, $D5, $00, $00, $00, $00, $00, $00, $00  ; voice 0 note codes

Whispering_Trees_Something_Moves_v0_vols:
    .byte $00, $00, $00, $05, $00, $00, $00, $00, $05, $00, $00, $00, $00, $00, $00, $00  ; voice 0 volumes

Whispering_Trees_Something_Moves_v1_notes:
    .byte $00, $B6, $00, $00, $00, $00, $00, $B5, $00, $00, $00, $00, $00, $B9, $00, $00  ; voice 1 note codes

Whispering_Trees_Something_Moves_v1_vols:
    .byte $00, $07, $00, $00, $00, $00, $00, $07, $00, $00, $00, $00, $00, $06, $00, $00  ; voice 1 volumes

; Pattern: Branches Creak (16 steps)
Whispering_Trees_Branches_Creak_len = 16

Whispering_Trees_Branches_Creak_v0_notes:
    .byte $CA, $00, $00, $00, $00, $00, $00, $00, $00, $00, $CC, $00, $00, $00, $00, $DE  ; voice 0 note codes

Whispering_Trees_Branches_Creak_v0_vols:
    .byte $05, $00, $00, $00, $00, $00, $00, $00, $00, $00, $05, $00, $00, $00, $00, $04  ; voice 0 volumes

Whispering_Trees_Branches_Creak_v1_notes:
    .byte $00, $00, $00, $00, $00, $00, $1C, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; voice 1 note codes

Whispering_Trees_Branches_Creak_v1_vols:
    .byte $00, $00, $00, $00, $00, $00, $07, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; voice 1 volumes

; ============================================================
; ARRANGEMENT TABLE
; Each entry = 9 bytes: v0_notes, v0_vols, v1_notes, v1_vols (words) + length (byte)
; ============================================================

Whispering_Trees_arrangement:
    ; arrangement[0] = Night Air
    .word Whispering_Trees_Night_Air_v0_notes
    .word Whispering_Trees_Night_Air_v0_vols
    .word Whispering_Trees_Night_Air_v1_notes
    .word Whispering_Trees_Night_Air_v1_vols
    .byte Whispering_Trees_Night_Air_len
    ; arrangement[1] = Rustling
    .word Whispering_Trees_Rustling_v0_notes
    .word Whispering_Trees_Rustling_v0_vols
    .word Whispering_Trees_Rustling_v1_notes
    .word Whispering_Trees_Rustling_v1_vols
    .byte Whispering_Trees_Rustling_len
    ; arrangement[2] = Night Air
    .word Whispering_Trees_Night_Air_v0_notes
    .word Whispering_Trees_Night_Air_v0_vols
    .word Whispering_Trees_Night_Air_v1_notes
    .word Whispering_Trees_Night_Air_v1_vols
    .byte Whispering_Trees_Night_Air_len
    ; arrangement[3] = Something Moves
    .word Whispering_Trees_Something_Moves_v0_notes
    .word Whispering_Trees_Something_Moves_v0_vols
    .word Whispering_Trees_Something_Moves_v1_notes
    .word Whispering_Trees_Something_Moves_v1_vols
    .byte Whispering_Trees_Something_Moves_len
    ; arrangement[4] = Rustling
    .word Whispering_Trees_Rustling_v0_notes
    .word Whispering_Trees_Rustling_v0_vols
    .word Whispering_Trees_Rustling_v1_notes
    .word Whispering_Trees_Rustling_v1_vols
    .byte Whispering_Trees_Rustling_len
    ; arrangement[5] = Branches Creak
    .word Whispering_Trees_Branches_Creak_v0_notes
    .word Whispering_Trees_Branches_Creak_v0_vols
    .word Whispering_Trees_Branches_Creak_v1_notes
    .word Whispering_Trees_Branches_Creak_v1_vols
    .byte Whispering_Trees_Branches_Creak_len
    ; arrangement[6] = Night Air
    .word Whispering_Trees_Night_Air_v0_notes
    .word Whispering_Trees_Night_Air_v0_vols
    .word Whispering_Trees_Night_Air_v1_notes
    .word Whispering_Trees_Night_Air_v1_vols
    .byte Whispering_Trees_Night_Air_len
    ; arrangement[7] = Something Moves
    .word Whispering_Trees_Something_Moves_v0_notes
    .word Whispering_Trees_Something_Moves_v0_vols
    .word Whispering_Trees_Something_Moves_v1_notes
    .word Whispering_Trees_Something_Moves_v1_vols
    .byte Whispering_Trees_Something_Moves_len
    ; arrangement[8] = Rustling
    .word Whispering_Trees_Rustling_v0_notes
    .word Whispering_Trees_Rustling_v0_vols
    .word Whispering_Trees_Rustling_v1_notes
    .word Whispering_Trees_Rustling_v1_vols
    .byte Whispering_Trees_Rustling_len
    ; arrangement[9] = Night Air
    .word Whispering_Trees_Night_Air_v0_notes
    .word Whispering_Trees_Night_Air_v0_vols
    .word Whispering_Trees_Night_Air_v1_notes
    .word Whispering_Trees_Night_Air_v1_vols
    .byte Whispering_Trees_Night_Air_len

; ── MUSIC_INIT_WHISPERING_TREES ──────────────────────────────────────────
; Set song parameters and reset playback to the beginning.
; Clobbers: A
MUSIC_INIT_WHISPERING_TREES:
    lda #<Whispering_Trees_arrangement
    sta MUS_ARR_PTR
    lda #>Whispering_Trees_arrangement
    sta MUS_ARR_PTR+1
    lda #Whispering_Trees_TEMPO
    sta MUS_TEMPO
    lda #Whispering_Trees_NUM_PATS
    sta MUS_NUM_PATS
    jsr MUSIC_INIT
    rts
