; ============================================================
; Atari 2600 Music Data
; Song: Shadows Gather — Forest of Mysteries OST
; Generated by Atari Sound Editor
; ============================================================

; NOTE CODE FORMAT: [driverCode(3 bits)][frequency(5 bits)]
; Driver codes:
;   000 = Square  (AUDC=4)    001 = Bass    (AUDC=6)
;   010 = Pitfall (AUDC=7)    011 = Noise   (AUDC=8)
;   100 = Buzz    (AUDC=15)   101 = Lead    (AUDC=12)
;   110 = Saw     (AUDC=1)    111 = Engine  (AUDC=3)
;   $00 = Rest (silence)

MUSIC_TEMPO     = 7   ; frames per step (NTSC 60fps)
MUSIC_NUM_PATS  = 9

; ============================================================
; PATTERN DATA
; ============================================================

; Pattern: Into Darkness (16 steps)
Shadows_Gather_Into_Darkness_len = 16

Shadows_Gather_Into_Darkness_v0_notes:
    .byte $CA, $00, $00, $00, $CC, $00, $00, $00, $CA, $00, $00, $9E, $CC, $00, $00, $00  ; voice 0 note codes

Shadows_Gather_Into_Darkness_v0_vols:
    .byte $07, $00, $00, $00, $07, $00, $00, $00, $07, $00, $00, $08, $07, $00, $00, $00  ; voice 0 volumes

Shadows_Gather_Into_Darkness_v1_notes:
    .byte $BE, $00, $BC, $00, $B9, $00, $BC, $00, $BE, $00, $B5, $00, $00, $B9, $00, $BE  ; voice 1 note codes

Shadows_Gather_Into_Darkness_v1_vols:
    .byte $09, $00, $09, $00, $09, $00, $09, $00, $09, $00, $09, $00, $00, $08, $00, $07  ; voice 1 volumes

; Pattern: Omen (16 steps)
Shadows_Gather_Omen_len = 16

Shadows_Gather_Omen_v0_notes:
    .byte $CC, $00, $00, $9E, $DE, $00, $00, $00, $CC, $00, $9E, $00, $CA, $00, $00, $9E  ; voice 0 note codes

Shadows_Gather_Omen_v0_vols:
    .byte $07, $00, $00, $08, $06, $00, $00, $00, $07, $00, $08, $00, $07, $00, $00, $07  ; voice 0 volumes

Shadows_Gather_Omen_v1_notes:
    .byte $B5, $00, $B6, $00, $B9, $00, $00, $BE, $00, $B9, $BC, $00, $BE, $00, $00, $00  ; voice 1 note codes

Shadows_Gather_Omen_v1_vols:
    .byte $09, $00, $09, $00, $09, $00, $00, $09, $00, $09, $09, $00, $09, $00, $00, $00  ; voice 1 volumes

; Pattern: Forest Beckons (16 steps)
Shadows_Gather_Forest_Beckons_len = 16

Shadows_Gather_Forest_Beckons_v0_notes:
    .byte $CA, $00, $00, $00, $00, $CC, $00, $00, $9E, $00, $CA, $00, $00, $00, $00, $9E  ; voice 0 note codes

Shadows_Gather_Forest_Beckons_v0_vols:
    .byte $07, $00, $00, $00, $00, $06, $00, $00, $08, $00, $07, $00, $00, $00, $00, $07  ; voice 0 volumes

Shadows_Gather_Forest_Beckons_v1_notes:
    .byte $00, $1C, $00, $00, $B9, $00, $00, $BC, $00, $00, $BE, $00, $B5, $00, $00, $00  ; voice 1 note codes

Shadows_Gather_Forest_Beckons_v1_vols:
    .byte $00, $09, $00, $00, $09, $00, $00, $09, $00, $00, $09, $00, $08, $00, $00, $00  ; voice 1 volumes

; ============================================================
; ARRANGEMENT TABLE
; Each entry = 4 pointers: v0_notes, v0_vols, v1_notes, v1_vols
; ============================================================

Shadows_Gather_arrangement:
    ; arrangement[0] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[1] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[2] = Omen
    .word Shadows_Gather_Omen_v0_notes
    .word Shadows_Gather_Omen_v0_vols
    .word Shadows_Gather_Omen_v1_notes
    .word Shadows_Gather_Omen_v1_vols
    .byte Shadows_Gather_Omen_len
    ; arrangement[3] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[4] = Forest Beckons
    .word Shadows_Gather_Forest_Beckons_v0_notes
    .word Shadows_Gather_Forest_Beckons_v0_vols
    .word Shadows_Gather_Forest_Beckons_v1_notes
    .word Shadows_Gather_Forest_Beckons_v1_vols
    .byte Shadows_Gather_Forest_Beckons_len
    ; arrangement[5] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[6] = Omen
    .word Shadows_Gather_Omen_v0_notes
    .word Shadows_Gather_Omen_v0_vols
    .word Shadows_Gather_Omen_v1_notes
    .word Shadows_Gather_Omen_v1_vols
    .byte Shadows_Gather_Omen_len
    ; arrangement[7] = Forest Beckons
    .word Shadows_Gather_Forest_Beckons_v0_notes
    .word Shadows_Gather_Forest_Beckons_v0_vols
    .word Shadows_Gather_Forest_Beckons_v1_notes
    .word Shadows_Gather_Forest_Beckons_v1_vols
    .byte Shadows_Gather_Forest_Beckons_len
    ; arrangement[8] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len

; ============================================================
; MUSIC ENGINE
; ============================================================
; Required zero-page RAM:
;   MUS_FRAME   - frame countdown (1 byte)
;   MUS_STEP    - step within pattern (1 byte)
;   MUS_PAT_IDX - arrangement index (1 byte)
;   MUS_PLAYING - 0=stopped, 1=playing (1 byte)
;   MUS_PTR     - temp zero-page pointer (2 bytes)
; Required RAM addresses: AUDV0, AUDV1, AUDF0, AUDF1, AUDC0, AUDC1
; ============================================================

; Driver code → TIA AUDC lookup table
musCtrlTable:
    .byte 4, 6, 7, 8, 15, 12, 1, 3

; ── MUSIC_INIT ─────────────────────────────────────────────────────────
; Call once at startup to begin playback from the beginning
MUSIC_INIT:
    lda #MUSIC_TEMPO
    sta MUS_FRAME
    lda #0
    sta MUS_STEP
    sta MUS_PAT_IDX
    lda #1
    sta MUS_PLAYING
    rts

; ── MUSIC_STOP ─────────────────────────────────────────────────────────
MUSIC_STOP:
    lda #0
    sta MUS_PLAYING
    sta AUDV0
    sta AUDV1
    rts

; ── MUSIC_UPDATE ───────────────────────────────────────────────────────
; Call once per frame (during vertical blank recommended)
MUSIC_UPDATE:
    lda MUS_PLAYING
    beq .musEnd
    dec MUS_FRAME
    bne .musEnd
    lda #MUSIC_TEMPO
    sta MUS_FRAME

    ; Calculate arrangement entry offset (5 bytes per entry)
    lda MUS_PAT_IDX
    asl         ; *2
    asl         ; *4
    clc
    adc MUS_PAT_IDX ; +idx = *5
    tax

    ; Get current step
    ldy MUS_STEP

    ; ── Voice 0 note ─────────────────────────────
    lda Shadows_Gather_arrangement,x
    sta MUS_PTR
    lda Shadows_Gather_arrangement+1,x
    sta MUS_PTR+1
    lda (MUS_PTR),y     ; load note code
    beq .v0Silence
    pha
    lsr 
    lsr 
    lsr 
    lsr 
    lsr ; driver code → X
    tax
    lda musCtrlTable,x
    sta AUDC0
    pla
    and #%00011111
    sta AUDF0
    ; volume
    lda Shadows_Gather_arrangement+2,x
    sta MUS_PTR
    lda Shadows_Gather_arrangement+3,x
    sta MUS_PTR+1
    lda (MUS_PTR),y
    sta AUDV0
    jmp .v1Note
.v0Silence:
    lda #0
    sta AUDV0

    ; ── Voice 1 note ─────────────────────────────
.v1Note:
    lda Shadows_Gather_arrangement+5,x  ; next entry pointer (v1 notes, +5*n bytes)
    ; NOTE: adjust indexing to match your assembler's word size
    ; (simplified — see documentation for full dual-voice driver)

    ; ── Advance step ──────────────────────────────
    inc MUS_STEP
    lda Shadows_Gather_arrangement+4,x  ; pattern length
    cmp MUS_STEP
    bne .musEnd
    lda #0
    sta MUS_STEP
    inc MUS_PAT_IDX
    lda MUS_PAT_IDX
    cmp #MUSIC_NUM_PATS
    bne .musEnd
    lda #0
    sta MUS_PAT_IDX
.musEnd:
    rts